export const authorityHubs = [
  {
    slug: "lake-george-boating.html", title: "Lake George Boating", label: "Lake George", kind: "destination",
    image: "assets/editorial/lake-george-cruise.jpg",
    intro: "Plan better days on Lake George with practical guidance for launches, islands, weather, family stops and the decisions that make a mountain-lake weekend run smoothly.",
    articles: [
      ["lake-george-boat-launches.html", "Lake George Boat Launches: How to Choose and Prepare", "Compare launch-day logistics, parking, timing and the checks to make before towing north."],
      ["lake-george-island-camping.html", "Lake George Island Camping by Boat", "Build a realistic island-camping plan around reservations, loading, weather and leave-no-trace habits."],
      ["lake-george-family-weekend.html", "A Family Boating Weekend on Lake George", "A flexible two-day itinerary with short runs, swim time and bad-weather alternatives."],
      ["lake-george-navigation-hazards.html", "Lake George Navigation Hazards and No-Wake Planning", "Use charts, markers, lookout discipline and conservative speed to avoid common route mistakes."],
    ],
  },
  {
    slug: "thousand-islands-boating.html", title: "Thousand Islands Boating", label: "Thousand Islands", kind: "destination",
    image: "assets/editorial/thousand-islands-river.jpg",
    intro: "Navigate the Thousand Islands with a plan for current, borders, narrow channels, castles, village stops and protected alternatives when the river turns rough.",
    articles: [
      ["thousand-islands-first-trip.html", "Your First Thousand Islands Boating Trip", "Choose a home base, manageable route and first-day shakedown cruise."],
      ["thousand-islands-castles-by-boat.html", "Visiting Thousand Islands Castles by Boat", "Plan dock approaches, admission timing and nearby stops without overloading the day."],
      ["thousand-islands-border-crossing.html", "Cross-Border Boating in the Thousand Islands", "Understand the documents, reporting questions and planning habits to verify before departure."],
      ["thousand-islands-current-navigation.html", "Current, Channels and Navigation in the Thousand Islands", "Read the river, anticipate traffic and avoid letting scenery outrun situational awareness."],
    ],
  },
  {
    slug: "finger-lakes-boating.html", title: "Finger Lakes Boating", label: "Finger Lakes", kind: "destination",
    image: "assets/editorial/finger-lakes-seneca.jpg",
    intro: "Choose the right Finger Lake and shape a weekend around long fetch, changing wind, waterfront towns, launch access and Central New York family travel.",
    articles: [
      ["finger-lakes-which-lake.html", "Which Finger Lake Is Best for Your Boat?", "Match lake size, shoreline services and trip style to your boat and crew."],
      ["seneca-lake-boating.html", "Seneca Lake Boating Guide", "Plan long-water routes, harbor stops and conservative returns on the region’s largest-feeling reaches."],
      ["cayuga-lake-boating.html", "Cayuga Lake Boating Guide", "Connect launches, Ithaca-area stops and weather-aware day routes."],
      ["finger-lakes-family-itinerary.html", "Finger Lakes Family Boating Itinerary", "Combine a manageable cruise with shore time, food and a weather-proof backup plan."],
    ],
  },
  {
    slug: "great-lakes-boating.html", title: "Great Lakes Boating", label: "Great Lakes", kind: "destination",
    image: "assets/editorial/lake-ontario-fair-haven-hero.webp",
    intro: "Treat the Great Lakes like the inland seas they are: plan for cold water, fast weather, commercial traffic, long distances and harbors that may be farther apart than they look.",
    articles: [
      ["great-lakes-first-trip.html", "Planning a First Great Lakes Boating Trip", "Start with conservative water, short harbor hops and serious weather margins."],
      ["great-lakes-cold-water.html", "Cold-Water Safety on the Great Lakes", "Plan clothing, flotation and recovery around water temperature rather than sunshine."],
      ["great-lakes-harbor-hopping.html", "Great Lakes Harbor-Hopping Basics", "Build routes around refuge, fuel, daylight and changing conditions."],
      ["great-lakes-weather-planning.html", "Reading Great Lakes Marine Weather", "Translate zone forecasts, wind direction and wave period into a boat-specific decision."],
    ],
  },
  {
    slug: "hudson-river-boating.html", title: "Hudson River Boating", label: "Hudson River", kind: "destination",
    image: "assets/editorial/hudson-river-bear-mountain-hero.webp",
    intro: "Explore the Hudson with a working understanding of current, tides, commercial traffic, bridges, marinas and the dramatic shoreline between New York Harbor and the canal system.",
    articles: [
      ["hudson-river-first-trip.html", "Your First Hudson River Boating Trip", "Choose a manageable reach and learn the river before building a longer itinerary."],
      ["hudson-river-tides-current.html", "Hudson River Tides and Current Explained", "Use predictions and observations to improve timing, fuel planning and docking."],
      ["hudson-river-marina-planning.html", "Hudson River Marina and Fuel Planning", "Verify transient space, fuel type, approach depth and after-hours procedures."],
      ["hudson-river-weekend-itinerary.html", "A Hudson River Boating Weekend", "A flexible itinerary framework that leaves room for current, weather and shore time."],
    ],
  },
  {
    slug: "intracoastal-waterway.html", title: "Intracoastal Waterway", label: "Intracoastal Waterway", kind: "destination",
    image: "assets/editorial/intracoastal-ft-lauderdale-hero.webp",
    intro: "Prepare for the Intracoastal Waterway with route segments, bridge timing, shallow-water awareness, marina communication and the daily discipline long-distance cruising demands.",
    articles: [
      ["icw-first-timer.html", "The Intracoastal Waterway for First-Timers", "Understand the rhythm of bridge openings, navigation checks and daily mileage."],
      ["icw-shoaling-navigation.html", "ICW Shoaling and Navigation Planning", "Use current notices, charts and conservative piloting where the channel moves."],
      ["icw-marina-reservations.html", "Planning ICW Marinas and Overnight Stops", "Balance reservations with weather flexibility, fuel range and arrival timing."],
      ["icw-packing-checklist.html", "ICW Packing and Spare-Parts Checklist", "Carry the tools, documents and consumables that keep routine problems small."],
    ],
  },
  {
    slug: "boat-ownership.html", title: "Boat Ownership", label: "Boat Ownership", kind: "ownership",
    image: "assets/editorial/journal-family-pontoon.jpg",
    intro: "Own a boat with fewer surprises by understanding the true calendar, cost, paperwork, storage, maintenance and habits behind dependable weekends on the water.",
    articles: [
      ["true-cost-of-boat-ownership.html", "The True Cost of Boat Ownership", "Build an annual budget that includes the expenses buyers usually overlook."],
      ["boat-insurance-explained.html", "Boat Insurance Explained for New Owners", "Compare coverage questions, navigation limits, deductibles and lay-up terms."],
      ["first-season-boat-owner.html", "Your First Season as a Boat Owner", "A month-by-month plan for learning the boat without letting maintenance pile up."],
      ["boat-records-and-logbook.html", "Boat Records and Logbook System", "Keep service, fuel, trips, equipment and documents organized in one useful system."],
    ],
  },
  {
    slug: "boat-buying.html", title: "Boat Buying", label: "Boat Buying", kind: "ownership",
    image: "assets/editorial/journal-boat-show.jpg",
    intro: "Buy the boat that fits your real water, crew and storage—not the fantasy created by a showroom—using total-cost thinking and a disciplined inspection process.",
    articles: [
      ["buying-your-first-boat.html", "Buying Your First Boat", "Turn intended use, crew size and local water into a realistic short list."],
      ["used-boat-inspection-checklist.html", "Used Boat Inspection Checklist", "Screen condition, systems, documents and warning signs before paying for a survey."],
      ["boat-sea-trial-guide.html", "How to Conduct a Useful Boat Sea Trial", "Test cold start, handling, systems and operating behavior under realistic conditions."],
      ["boat-financing-guide.html", "Boat Financing Without Fooling Yourself", "Compare payment, term, depreciation and cash reserve as one ownership decision."],
    ],
  },
  {
    slug: "boat-maintenance.html", title: "Boat Maintenance", label: "Maintenance", kind: "maintenance",
    image: "assets/editorial/journal-engine-maintenance.jpg",
    intro: "Keep the boat ready through small, repeatable inspections and service intervals that catch corrosion, leaks, weak batteries and cooling problems before launch morning.",
    articles: [
      ["boat-maintenance-schedule.html", "The Complete Recreational Boat Maintenance Schedule", "Organize checks by trip, month, engine hours and season."],
      ["outboard-engine-maintenance.html", "Outboard Engine Maintenance Basics", "Protect fuel, cooling, lubrication and starting systems with consistent care."],
      ["inboard-sterndrive-maintenance.html", "Inboard and Sterndrive Maintenance Basics", "Track bellows, fluids, cooling and corrosion risks that are easy to postpone."],
      ["spring-commissioning-checklist.html", "Spring Commissioning Checklist", "Bring systems online methodically and leave time for corrections before the first trip."],
    ],
  },
  {
    slug: "boat-electronics.html", title: "Boat Electronics", label: "Boat Electronics", kind: "gear",
    image: "assets/chartplotter.svg",
    intro: "Choose and operate marine electronics as a connected navigation and communication system, with power, installation, compatibility and operator skill considered together.",
    articles: [
      ["marine-electronics-explained.html", "Marine Electronics Explained", "Understand the roles of chartplotters, sonar, radar, AIS and VHF."],
      ["choosing-vhf-radio.html", "Choosing a VHF Marine Radio", "Compare fixed and handheld radios, DSC capability, antenna systems and backup use."],
      ["ais-for-recreational-boats.html", "AIS for Recreational Boats", "Know what AIS shows, what it misses and when receive-only or transceive capability makes sense."],
      ["marine-electronics-installation.html", "Planning a Marine Electronics Installation", "Design power, networking, transducer and display placement before drilling holes."],
    ],
  },
  {
    slug: "boating-safety.html", title: "Boating Safety", label: "Safety", kind: "seamanship",
    image: "assets/editorial/gear-life-jacket.jpg",
    intro: "Build safety around normal boat operation: fitted life jackets, capable crew, conservative weather calls, practiced emergencies and equipment everyone can actually reach.",
    articles: [
      ["predeparture-safety-checklist.html", "Predeparture Boating Safety Checklist", "Use a short repeatable check for weather, fuel, equipment, crew and float-plan details."],
      ["person-overboard-recovery.html", "Person-Overboard Recovery for Recreational Boats", "Plan how your actual crew will stop, return, make contact and recover a person."],
      ["boating-with-children-safely.html", "Boating Safely With Children", "Fit flotation, set movement rules and design the day around children’s limits."],
      ["night-boating-safety.html", "Night Boating Safety", "Reduce speed, preserve night vision and manage lights, lookout and navigation workload."],
    ],
  },
  {
    slug: "docking.html", title: "Docking", label: "Docking", kind: "seamanship",
    image: "assets/editorial/journal-dock-lines.jpg",
    intro: "Make docking slower, quieter and more predictable by planning the approach, assigning lines, reading wind and current, and using briefings instead of shouted improvisation.",
    articles: [
      ["how-to-dock-in-wind.html", "How to Dock a Boat in Wind", "Use angle, momentum and spring lines to manage a wind-affected approach."],
      ["dock-lines-explained.html", "Dock Lines Explained", "Rig bow, stern, breast and spring lines for the movement the boat must resist."],
      ["docking-single-handed.html", "Single-Handed Docking", "Prepare lines and fenders so one controlled stop replaces several rushed tasks."],
      ["fuel-dock-etiquette.html", "Fuel Dock Etiquette and Safety", "Approach prepared, fuel safely and clear the working dock without unnecessary delay."],
    ],
  },
  {
    slug: "anchoring.html", title: "Anchoring", label: "Anchoring", kind: "seamanship",
    image: "assets/editorial/anchored-powerboat-photo-hero.webp",
    intro: "Anchor with confidence by matching ground tackle to the bottom, setting it deliberately, calculating scope from the correct height and monitoring the boat after everyone relaxes.",
    articles: [
      ["how-to-anchor-a-boat.html", "How to Anchor a Boat Correctly", "Choose the spot, lower under control, set the anchor and verify holding."],
      ["anchor-scope-calculator-guide.html", "Anchor Scope Explained", "Calculate scope using total depth and understand when more rode is needed."],
      ["choosing-boat-anchor.html", "Choosing the Right Boat Anchor", "Match design, size and backup strategy to the boat and expected bottoms."],
      ["overnight-anchoring-checklist.html", "Overnight Anchoring Checklist", "Plan swing room, alarms, weather changes, lights and an exit route before dark."],
    ],
  },
  {
    slug: "marine-weather.html", title: "Marine Weather", label: "Weather", kind: "seamanship",
    image: "assets/editorial/chesapeake-sailing.jpg",
    intro: "Turn forecasts into conservative boat decisions by combining official products, wind direction, fetch, waves, visibility, water temperature and shelter along the route.",
    articles: [
      ["how-to-read-marine-forecast.html", "How to Read a Marine Forecast", "Translate forecast zones, timing and advisories into limits for your boat."],
      ["wind-waves-and-fetch.html", "Wind, Waves and Fetch Explained", "Understand why direction and distance across water can matter more than one wind number."],
      ["thunderstorm-planning-boaters.html", "Thunderstorm Planning for Boaters", "Build early exit triggers and shelter choices before convective weather develops."],
      ["cold-water-boating.html", "Cold-Water Boating Risk", "Dress and plan for immersion even when the air feels warm."],
    ],
  },
  {
    slug: "marine-navigation.html", title: "Marine Navigation", label: "Navigation", kind: "seamanship",
    image: "assets/chartplotter.svg",
    intro: "Navigate by combining charts, aids, position awareness, lookout and a route plan that still works when electronics, visibility or assumptions fail.",
    articles: [
      ["how-to-read-nautical-chart.html", "How to Read a Nautical Chart", "Understand depth, hazards, aids and notes without treating the screen as a moving road map."],
      ["navigation-rules-of-road.html", "Boating Rules of the Road", "Learn the meeting, crossing and overtaking responsibilities behind predictable maneuvers."],
      ["buoys-and-navigation-markers.html", "Buoys and Navigation Markers Explained", "Read lateral aids, regulatory marks and local systems before entering unfamiliar water."],
      ["float-plan-guide.html", "How to Make a Useful Float Plan", "Leave route, crew, boat and overdue-action information someone ashore can actually use."],
    ],
  },
  {
    slug: "family-boating.html", title: "Family Boating", label: "Family Boating", kind: "family",
    image: "assets/editorial/journal-family-pontoon.jpg",
    intro: "Create family boating days that children want to repeat by shortening the agenda, protecting comfort, sharing small jobs and planning shore time as carefully as the cruise.",
    articles: [
      ["first-boat-trip-with-kids.html", "The First Boat Trip With Kids", "Keep the first outing short, comfortable and focused on one memorable success."],
      ["family-boat-packing-list.html", "Family Boat Packing List", "Pack sun, warmth, food, flotation and simple entertainment without burying safety gear."],
      ["kids-jobs-on-a-boat.html", "Safe Jobs for Kids on a Boat", "Give children useful age-appropriate roles that build awareness and confidence."],
      ["family-boating-weekend.html", "How to Plan a Family Boating Weekend", "Balance cruise time, swimming, meals, sleep and weather alternatives."],
    ],
  },
  {
    slug: "pontoon-boats.html", title: "Pontoon Boats", label: "Pontoon Boats", kind: "boat-type",
    image: "assets/editorial/journal-family-pontoon.jpg",
    intro: "Understand pontoon layouts, power, capacity, trailering and handling so the platform fits the family’s real water and not merely the dealership seating test.",
    articles: [
      ["pontoon-buying-guide.html", "Pontoon Boat Buying Guide", "Compare size, tube configuration, power, layout and total rigging cost."],
      ["pontoon-horsepower-guide.html", "How Much Horsepower Does a Pontoon Need?", "Match performance expectations and load to a sensible power range."],
      ["pontoon-docking-tips.html", "Pontoon Docking and Wind Tips", "Manage windage with deliberate angles, prepared lines and slower decisions."],
      ["pontoon-maintenance.html", "Pontoon Boat Maintenance", "Care for tubes, deck, upholstery, engine, cover and trailer through the season."],
    ],
  },
  {
    slug: "fishing-boats.html", title: "Fishing Boats", label: "Fishing Boats", kind: "boat-type",
    image: "assets/editorial/center-console-underway-photo-hero.webp",
    intro: "Choose a fishing boat around target water, weather, crew and technique while preserving the safety, storage and ride quality needed to enjoy non-fishing days too.",
    articles: [
      ["fishing-boat-buying-guide.html", "Fishing Boat Buying Guide", "Compare hull, layout, livewell, electronics and power for the fishing you actually do."],
      ["fish-finder-basics.html", "Fish Finder Basics", "Understand sonar frequencies, transducers and screen interpretation before upgrading."],
      ["trolling-motor-buying-guide.html", "Trolling Motor Buying Guide", "Match thrust, shaft length, voltage and control features to the boat."],
      ["fishing-boat-safety.html", "Fishing Boat Safety and Deck Organization", "Keep hooks, lines, batteries and moving anglers from creating avoidable hazards."],
    ],
  },
  {
    slug: "boat-trailering.html", title: "Boat Trailering", label: "Trailering", kind: "ownership",
    image: "assets/editorial/boat-trailer-ramp-photo-hero.webp",
    intro: "Trailer with less stress by confirming ratings, maintaining bearings and brakes, practicing setup and using repeatable launch and retrieval routines.",
    articles: [
      ["boat-trailer-safety-checklist.html", "Boat Trailer Safety Checklist", "Inspect hitch, tires, bearings, brakes, lights and tie-downs before every tow."],
      ["launching-boat-from-trailer.html", "How to Launch a Boat From a Trailer", "Stage away from the ramp and use a calm driver-operator handoff."],
      ["retrieving-boat-on-trailer.html", "How to Retrieve a Boat on a Trailer", "Line up, control depth and secure the boat without occupying the ramp longer than needed."],
      ["trailer-bearing-maintenance.html", "Boat Trailer Bearing Maintenance", "Recognize heat, water intrusion and service intervals before a roadside failure."],
    ],
  },
  {
    slug: "boat-winterization.html", title: "Boat Winterization", label: "Winterization", kind: "maintenance",
    image: "assets/editorial/journal-winter-storage.jpg",
    intro: "Put the boat away so spring starts with commissioning rather than repair, protecting fuel, cooling systems, batteries, plumbing, upholstery and ventilation.",
    articles: [
      ["outboard-winterization.html", "Outboard Motor Winterization", "Stabilize fuel, protect the engine and follow model-specific storage requirements."],
      ["sterndrive-winterization.html", "Sterndrive Winterization", "Address freeze risk, fluids, corrosion and drive components deliberately."],
      ["boat-battery-winter-storage.html", "Boat Battery Winter Storage", "Clean, charge, isolate and monitor batteries through the off-season."],
      ["boat-cover-winter-storage.html", "Boat Covers and Winter Storage", "Choose support, ventilation and snow-load management that protect rather than trap damage."],
    ],
  },
];
