export const catalog = {
  destinations: [
    ["canadarago-lake-family-boating.html", "Canadarago Lake Family Boat Plan"],
    ["butterfield-lake-family-boating.html", "Butterfield Lake Family Boat Plan"],
    ["oswego-harbor-family-boating.html", "Oswego Harbor Family Boat Plan"],
    ["little-falls-erie-canal-family-boating.html", "Little Falls Erie Canal Family Boat Plan"],
    ["schroon-lake-family-boating.html", "Schroon Lake Family Boat Plan"],
    ["saratoga-lake-family-boating.html", "Saratoga Lake Family Boat Plan"],
    ["black-lake-family-boating.html", "Black Lake Family Boat Plan"],
    ["cranberry-lake-family-boating.html", "Cranberry Lake Family Boat Plan"],
    ["tupper-lake-family-boating.html", "Tupper Lake Family Boat Plan"],
    ["otsego-lake-family-boating.html", "Otsego Lake Family Boat Plan"],
    ["great-sacandaga-lake-family-boating.html", "Great Sacandaga Lake Family Boat Plan"],
    ["sodus-bay-family-boating.html", "Sodus Bay Family Boat Plan"],
    ["delta-lake-family-boating.html", "Delta Lake Family Boat Plan"],
    ["lower-saranac-lake-family-boating.html", "Lower Saranac Lake Family Boat Plan"],
    ["cayuga-lake-state-park-family-boating.html", "Cayuga Lake State Park Family Boat Plan"],
    ["honeoye-lake-family-boating.html", "Honeoye Lake Family Boat Plan"],
    ["fair-haven-little-sodus-bay-family-boating.html", "Little Sodus Bay From Fair Haven"],
    ["chautauqua-lake-long-point-family-boating.html", "Chautauqua Lake From Long Point"],
    ["blenheim-gilboa-lower-reservoir-family-boating.html", "Blenheim-Gilboa Lower Reservoir Family Boat Plan"],
    ["canandaigua-lake-family-boating.html", "Canandaigua Lake Family Boat Plan"],
    ["owasco-lake-family-boating.html", "Owasco Lake Family Boat Plan"],
    ["keuka-lake-family-boating.html", "Keuka Lake Family Boat Plan"],
    ["otisco-lake-family-boating.html", "Otisco Lake Family Boat Plan"],
    ["oneida-lake-family-boating.html", "Oneida Lake Family Boat Plan"],
    ["skaneateles-lake-family-boating.html", "Skaneateles Lake Family Boat Plan"],
    ["lake-george-guide.html", "Lake George Weekend Guide"],
    ["thousand-islands-guide.html", "Thousand Islands Cruising Guide"],
    ["finger-lakes-guide.html", "Finger Lakes Boating Guide"],
    ["lake-champlain-guide.html", "Lake Champlain Cruising Guide"],
    ["lake-winnipesaukee-guide.html", "Lake Winnipesaukee Guide"],
    ["newport-rhode-island-guide.html", "Newport by Boat"],
    ["cape-cod-guide.html", "Cape Cod Boating Guide"],
    ["chesapeake-bay-guide.html", "Chesapeake Bay Cruising Guide"],
    ["erie-canal-guide.html", "Erie Canal Boating Guide"],
  ],
  guides: [
    ["boat-moisture-meter-pinless-pin-guide.html", "Boat Moisture Meter Selection Guide"],
    ["boat-drain-plug-transom-garboard-guide.html", "Boat Drain-Plug Fit Guide"],
    ["boat-spare-propeller-kit-guide.html", "Boat Spare-Propeller System Guide"],
    ["boat-battery-monitor-shunt-voltage-bluetooth-guide.html", "Boat Battery Monitor Guide"],
    ["boat-engine-cutoff-switch-lanyard-wireless-guide.html", "Boat Engine Cutoff Switch Guide"],
    ["boat-trailer-security-coupler-wheel-lock-guide.html", "Boat Trailer Security Layers Guide"],
    ["boat-trailer-spare-tire-system-guide.html", "Boat Trailer Spare-Tire System Guide"],
    ["boat-battery-box-tray-hold-down-guide.html", "Boat Battery Securement Guide"],
    ["outboard-engine-flushing-methods-guide.html", "Outboard Engine Flushing Methods"],
    ["boat-trailer-transom-straps-guide.html", "Boat Trailer Transom-Strap Guide"],
    ["boat-trailer-tongue-jack-guide.html", "Boat Trailer Tongue-Jack Guide"],
    ["boat-trailer-winch-strap-guide.html", "Boat Trailer Winch and Strap Guide"],
    ["boat-flashlight-spotlight-headlamp-guide.html", "Boat Flashlight and Spotlight Guide"],
    ["boat-bilge-pump-buying-guide.html", "Boat Bilge-Pump System Guide"],
    ["boat-dry-bag-waterproof-case-guide.html", "Boat Dry Storage Guide"],
    ["boat-portable-jump-starter-guide.html", "Boat Portable Jump Starter Guide"],
    ["marine-carbon-monoxide-alarm-guide.html", "Marine Carbon Monoxide Alarm Guide"],
    ["boat-anchor-rode-buying-guide.html", "Boat Anchor Rode Buying Guide"],
    ["boat-boarding-ladder-buying-guide.html", "Boat Boarding Ladder Buying Guide"],
    ["boat-navigation-lights-buying-guide.html", "Boat Navigation Lights Buying Guide"],
    ["boat-horn-sound-signal-guide.html", "Boat Horn and Sound Signal Guide"],
    ["boat-fire-extinguisher-guide.html", "Boat Fire Extinguisher Guide"],
    ["boat-tool-kit-guide.html", "Boat Tool Kit Guide"],
    ["boat-flares-electronic-distress-signal-guide.html", "Boat Visual Distress Signal Guide"],
    ["boat-throwable-flotation-device-guide.html", "Boat Throwable Flotation Device Guide"],
    ["marine-binoculars-buying-guide.html", "Marine Binoculars Buying Guide"],
    ["best-chartplotters.html", "Best Marine Chartplotters"],
    ["best-boat-coolers.html", "Best Boat Coolers"],
    ["best-life-jackets.html", "Best Life Jackets for Boating"],
  ],
  journal: [
    ["boat-capacity-plate-persons-weight-horsepower-guide.html", "Boat Capacity-Plate Loading Guide"],
    ["new-york-boat-registration-documents-guide.html", "New York Boat Registration Documents"],
    ["swimming-from-boat-with-kids-safety-plan.html", "Family Swim-Off-Boat Safety Plan"],
    ["boat-tow-vs-salvage-assistance-guide.html", "Boat Tow vs Salvage Guide"],
    ["boat-runs-aground-response.html", "Boat Grounding Response Matrix"],
    ["used-boat-title-hin-paperwork-guide.html", "Used Boat Title, HIN and Paperwork Guide"],
    ["rope-in-boat-propeller-response.html", "Rope-in-Propeller Response"],
    ["gasoline-odor-boat-response.html", "Gasoline-Odor Response"],
    ["towing-tube-with-kids-safety-plan.html", "Family Tubing Safety Plan"],
    ["boat-engine-overheat-warning-response.html", "Boat Engine-Overheat Warning Response"],
    ["boat-engine-stall-response.html", "Boat Engine-Stall Response"],
    ["crossing-boat-wakes-family.html", "Crossing Boat Wakes With Family Aboard"],
    ["family-docking-crew-briefing.html", "Family Docking Crew Brief"],
    ["boat-submerged-object-strike-response.html", "Submerged-Object Strike Response"],
    ["boating-in-fog-restricted-visibility.html", "Boating in Fog and Restricted Visibility"],
    ["boat-steering-failure-response.html", "Boat Steering Failure Response"],
    ["classic-runabouts.html", "Why Classic Runabouts Still Matter"],
    ["chartplotter-needs.html", "How Much Chartplotter Do You Need?"],
    ["dock-box-essentials.html", "What Belongs in a Dock Box"],
    ["end-of-season-checklist.html", "The End-of-Season Checklist"],
    ["great-family-boat.html", "What Makes a Great Family Boat"],
    ["waterfront-escape.html", "How to Plan a Waterfront Escape"],
  ],
};

export function relatedSet(overrides = {}) {
  const rotate = (items, start = 0) => [...items.slice(start), ...items.slice(0, start)].slice(0, 3);
  return {
    destinations: overrides.destinations || rotate(catalog.destinations, overrides.destinationStart || 0),
    guides: overrides.guides || rotate(catalog.guides, overrides.guideStart || 0),
    journal: overrides.journal || rotate(catalog.journal, overrides.journalStart || 0),
  };
}
